name: Integration Checks

on:
  push:
    branches: 
    - develop
  pull_request:
    branches: 
    - develop

jobs:
  check-package:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a placeholder workflow."
